### ISSUE TITLE
Enable easier changing of the URL for novice users

### ISSUE THREAD

**Issue by Lewiscowles1986** [CODESIGN2/rpi-pixel-kiosk#2]
probably as simple as 

``` shell
ARGS=`cat /boot/url.txt`
```

to allow for additional options to be passed to the browser, but potential for `jq` and a single json format config file `appliance.json`

**Comment by chriso0710** [comment]
You might like to take a look at https://github.com/chriso0710/pikiosk, which fully automates a Chromium kiosk based on Raspbian Jessie with Ansible. It sets the URL for all your kiosk pis with a single command.

Christian

**Comment by Lewiscowles1986** [comment]
Thanks so much for reaching out. I love that it's ansible. I'd love even more if maybe we could both borrow ideas (I love the idea of using ansible as an option as well as shell-script)

**Comment by chriso0710** [comment]
Thanks, Lewis, for the friendly welcome! :-)

**Comment by Lewiscowles1986** [comment]
See https://github.com/CODESIGN2/rpi-pixel-kiosk/commit/3a7d188e39514e500c68b339e77ef3e80c5c02f3
